<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="cart_old.aspx.cs" Inherits="ShoppingCart" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">

    <p><br /><br /><br />
        Shopping Cart<br />
    </p>
    <p>
         <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4" Width="718px" AutoGenerateDeleteButton="True" Height="232px" ShowFooter="True" OnRowDeleting="GridView1_RowDeleting" >
            <Columns>
                <asp:BoundField DataField="gametitle" HeaderText="Title" SortExpression="gametitle"></asp:BoundField>
                <asp:BoundField DataField="consolename" HeaderText="Console" SortExpression="consolename"></asp:BoundField>
                <asp:BoundField DataField="gameyear" HeaderText="Release Year" SortExpression="gameyear"></asp:BoundField>
                <asp:BoundField DataField="gamegenre" HeaderText="Genre" SortExpression="gamegenre"></asp:BoundField>
                <asp:BoundField DataField="gamecompany" HeaderText="Company" SortExpression="gamecompany"></asp:BoundField>
                <asp:BoundField DataField="gamenumplayers" HeaderText="Number of Players" SortExpression="gamenumplayers"></asp:BoundField>
                <asp:BoundField DataField="gameprice" HeaderText="Price" SortExpression="gameprice"></asp:BoundField>
                <asp:BoundField DataField="quantityof" HeaderText="Quantity of Games"></asp:BoundField>
                <asp:BoundField DataField="LineTotal" HeaderText="Line Total"></asp:BoundField>
            </Columns>

            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#330099" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <SortedAscendingCellStyle BackColor="#FEFCEB" />
            <SortedAscendingHeaderStyle BackColor="#AF0101" />
            <SortedDescendingCellStyle BackColor="#F6F0C0" />
            <SortedDescendingHeaderStyle BackColor="#7E0000" />
        </asp:GridView>


    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:Button ID="btn_checkout" runat="server" OnClick="btn_checkout_Click" Text="Checkout" />
    </p>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
    </p>


</asp:Content>

